export const tourConfigs = {
  student: [
    {
      refKey: 'appBarTabs',
      emoji: '🧭',
      headline: 'Navigate Your Dashboard',
      description: 'Use these tabs to switch between your AI Tutor, Progress, and Orientation views.',
      position: 'bottom',
    },
    {
      refKey: 'attendancePanel',
      emoji: '📋',
      headline: 'Track Attendance',
      description: 'Check in and out daily. Your attendance record is visible to your teacher and counselor.',
      position: 'bottom',
    },
    {
      refKey: 'alertBanners',
      emoji: '🚨',
      headline: 'Important Alerts',
      description: 'Stay informed with school alerts and guidance that may require your attention.',
      position: 'bottom',
    },
    {
      refKey: 'aiTutorChat',
      emoji: '🤖',
      headline: 'AI Tutor Chat',
      description: 'Ask questions and get step-by-step explanations, examples, and sources when available.',
      position: 'top',
    },
    {
      refKey: 'subjectChips',
      emoji: '🎯',
      headline: 'Choose a Subject',
      description: 'Pick the subject tutor you want before asking your next question.',
      position: 'bottom',
    },
    {
      refKey: 'masteryBars',
      emoji: '📈',
      headline: 'Mastery Progress',
      description: 'Track your mastery levels across subjects and see how you improve over time.',
      position: 'left',
    },
  ],

  teacher: [
    {
      refKey: 'studentsTable',
      emoji: '👩‍🎓',
      headline: 'Your Students',
      description: 'Review your student roster and open their session history to understand learning needs.',
      position: 'bottom',
    },
    {
      refKey: 'aiTutorsTab',
      emoji: '⭐',
      headline: 'AI Tutors Tab',
      description: 'Switch here to view tutor performance and how students are engaging with AI support.',
      position: 'bottom',
    },
    {
      refKey: 'contentLibrary',
      emoji: '📚',
      headline: 'Content Library',
      description: 'Manage course documents used as learning sources. This tab powers stronger, grounded answers.',
      position: 'bottom',
    },
    {
      refKey: 'uploadButton',
      emoji: '⬆️',
      headline: 'Upload a Document',
      description: 'Upload PDFs and materials to enrich your tutor. You can add chapter, guidelines, and tags.',
      position: 'bottom',
    },
    {
      refKey: 'analyticsTab',
      emoji: '📊',
      headline: 'Analytics Tab',
      description: 'Track engagement, sessions, and outcomes over time to improve instruction.',
      position: 'bottom',
    },
  ],

  admin: [
    {
      refKey: 'kpiCards',
      emoji: '📊',
      headline: 'Key Metrics',
      description: 'Get a quick snapshot of platform activity across classrooms, teachers, students, and parents.',
      position: 'bottom',
    },
    {
      refKey: 'classroomsGrid',
      emoji: '🏫',
      headline: 'Classrooms Grid',
      description: 'Manage classrooms by grade, assign staff, and enroll students to enable the right AI tutors.',
      position: 'bottom',
    },
    {
      refKey: 'teachersPanel',
      emoji: '👩‍🏫',
      headline: 'Teachers Panel',
      description: 'Assign subjects to teachers so they can access the correct student data and content tools.',
      position: 'bottom',
    },
    {
      refKey: 'counselorList',
      emoji: '🧠',
      headline: 'Counselor List',
      description: 'See registered counselors and their status to support student guidance and interventions.',
      position: 'bottom',
    },
    {
      refKey: 'parentsPaymentsTable',
      emoji: '💳',
      headline: 'Parents & Payments',
      description: 'Review parent accounts and payment status, and open details when needed.',
      position: 'top',
    },
  ],

  parent: [
    {
      refKey: 'childSelector',
      emoji: '👧',
      headline: 'Select a Child',
      description: 'Switch between linked children to view progress, attendance, and recommendations.',
      position: 'bottom',
    },
    {
      refKey: 'linkChildButton',
      emoji: '🔗',
      headline: 'Link a Child',
      description: "Connect your child's account to unlock their dashboard and updates.",
      position: 'bottom',
    },
    {
      refKey: 'summaryCards',
      emoji: '🧾',
      headline: 'At-a-Glance Summary',
      description: 'Quickly check attendance rate, weekly sessions, tutor satisfaction, and grade level.',
      position: 'bottom',
    },
    {
      refKey: 'masteryBars',
      emoji: '📈',
      headline: 'Subject Mastery',
      description: 'See strengths and improvement areas based on your child’s learning progress.',
      position: 'bottom',
    },
    {
      refKey: 'attendancePie',
      emoji: '🥧',
      headline: 'Attendance Breakdown',
      description: 'A clear view of present vs late vs absent days over the selected timeframe.',
      position: 'top',
    },
    {
      refKey: 'alertsPanel',
      emoji: '🔔',
      headline: 'Alerts & Recommendations',
      description: 'Important warnings and guidance appear here so you can act early.',
      position: 'bottom',
    },
  ],

  counselor: [
    {
      refKey: 'allStudentsTable',
      emoji: '🧑‍🤝‍🧑',
      headline: 'All Students',
      description: 'Review student performance and spot risk signals across the school at a glance.',
      position: 'bottom',
    },
    {
      refKey: 'studentDetailsAction',
      emoji: '🔍',
      headline: 'Student Details',
      description: 'Open a full student profile including attendance, PFSM signals, and key summaries.',
      position: 'left',
    },
    {
      refKey: 'orientationAction',
      emoji: '🧭',
      headline: 'Orientation Insights',
      description: 'View recommendations and trigger fresh analysis to guide targeted interventions.',
      position: 'left',
    },
    {
      refKey: 'classroomsTab',
      emoji: '🏫',
      headline: 'Classrooms Tab',
      description: 'Switch to classroom view to filter and review students by class grouping.',
      position: 'bottom',
    },
  ],
};
